### ISSUE TITLE
Função gerar nosso_numero para o boleto

### ISSUE THREAD

**Issue by unixelias** [nxstep-si/nx-boletos#1]
Conferir validação do Nosso Número para o Boleto

**Comment by natancmacedo** [comment]
O "nosso número" é formado por 2 digitos do ano correspondente + 6 digitos que são o código do cedente (fixo). A função que calcula isso na classe foi modificada do original? Acredito que nesse caso do Sicoob seja mais simples que os outros bancos. Se não tiver sido modificada eu irei remove-la e fazer novamente.

**Comment by unixelias** [comment]
Na verdade seria a geração do DV para o campo. O Nosso Número do boleto é um número de registro com o formato: 2 dígitos para o ano e 5 dígitos de um registro único e sequencial dos boletos gerados naquele ano.
